version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
    - 27017:27017

  hotel:
    build: .
    container_name: hotel_api
    ports:
    - 8090:8090
    environment:
      - MONGODB_HOST=mongodb
    volumes:
    - ./src/:/java/app/src
    depends_on:
      - mongodb

