version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  hotel:
    build: .
    container_name: hotel_api
    ports:
    - 8090:8090
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/hotel
    volumes:
    - ./src/:/java/app/src
    depends_on:
      - mongodb

