/* DROP TABLE IF EXISTS USER; */
CREATE TABLE IF NOT EXISTS USER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL ,
    email VARCHAR(50) NOT NULL ,
    password VARCHAR(350) NOT NULL
);
/* DROP TABLE IF EXISTS ROOM; */
CREATE TABLE IF NOT EXISTS ROOM(
    id INT AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(50) NOT NULL ,
    price DOUBLE NOT NULL,
    booked VARCHAR(10) DEFAULT 'no'
);

/* DROP TABLE IF EXISTS CUSTOMER; */
CREATE TABLE IF NOT EXISTS CUSTOMER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    phone VARCHAR(20) DEFAULT NULL
);

DROP TABLE IF EXISTS BOOKING;
CREATE TABLE IF NOT EXISTS BOOKING(
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_number VARCHAR(20) NOT NULL,
    price DOUBLE NOT NULL,
    name VARCHAR(50) NOT NULL ,
    phone VARCHAR(20) DEFAULT NULL,
    email VARCHAR(50) NOT NULL,
    datetime VARCHAR(50) DEFAULT NULL
);