
### Authenticate

POST http://localhost:8090/api/v1/logins
Accept: application/json
Content-Type: application/json

{
  "username": "root@admin.com",
  "password": "root12"
}


### User post

POST http://localhost:8090/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNjE1NzQ5MjE2LCJpYXQiOjE2MTU3MzEyMTZ9.nvrTFKISS3jvZEumIpjMNzSGAPLbAqN_rvM8EY_C4CPtiahaNEVCGu8VSU3oTP4ipKcK7wlBmFdi-wpukSdd9w
Content-Type: application/json

{
  "email": "ali@yahoo.com",
  "password": "password"
}


### User get

GET http://localhost:8090/api/v1/users
Accept: application/json
Content-Type: application/json



### Room get

GET http://localhost:8090/api/v1/rooms
Accept: application/json
Content-Type: application/json



### Room post

POST http://localhost:8090/api/v1/rooms
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNjE1NzQ5MjE2LCJpYXQiOjE2MTU3MzEyMTZ9.nvrTFKISS3jvZEumIpjMNzSGAPLbAqN_rvM8EY_C4CPtiahaNEVCGu8VSU3oTP4ipKcK7wlBmFdi-wpukSdd9w
Content-Type: application/json

{
  "number": "0111",
  "price": 300.0
}
